config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
 resources :buckets do
  resources :tasks
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
    has_many :tasks, dependent: :destroy, :foreign_key => 'Bucket_id', :primary_key => 'id'
    validates :name, presence: true,
    length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :Bucket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
    def index
        @buckets = Bucket.all
      end
    def show
      puts "BAUCK> #{params}"
        @bucket = Bucket.find(params[:id])
      end
    def new
        @bucket = Bucket.new
    end
    def edit
      @bucket = Bucket.find(params[:id])
    end
    def create
      @bucket = Bucket.new(bucket_params)
     
      if @bucket.save
        redirect_to @bucket
      else
        render 'new'
      end
    end
    def update
      @bucket = Bucket.find(params[:id])
     
      if @bucket.update(bucket_params)
        redirect_to @bucket
      else
        render 'edit'
      end
    end
    def destroy
      @bucket = Bucket.find(params[:id])
      @bucket.destroy
   
      redirect_to buckets_path
    end
      private
  def bucket_params
    params.require(:bucket).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @bucket = Bucket.find(params[:bucket_id])
        @task = @bucket.tasks.create(task_params)
        redirect_to bucket_path(@bucket)
      end
      def destroy
        @bucket = Bucket.find(params[:bucket_id])
        @task = @bucket.tasks.find(params[:id])
        @task.destroy
        redirect_to bucket_path(@bucket)
      end
      private
        def task_params
          params.require(:task).permit(:name, :description)
        end
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buckets/_form.html.erb
<html style="background-color:#b8b894;">
<center>
<%= form_with model: @bucket, local: true do |form| %>
 
  <% if @bucket.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bucket.errors.count, "error") %> prohibited
        this bucket from being saved:
      </h2>
      <ul>
        <% @bucket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
  <b>  <%= form.label :name %><br> </b>
    <%= form.text_field :name %>
  </p>
 
  <p>
  <b>  <%= form.label :description %><br> </b>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit "Save"%>
  </p>

 
<% end %>
</center>
</html>

app/views/buckets/edit.html.erb
<html style="background-color:#b8b894;">
<center>
<h1 style="color:DodgerBlue; background-color:#00ff80;">Edit bucket</h1>
  <h2 style="color:DodgerBlue; background-color:#00ff80;">Enter the details to Update Buckets...</h2>

<%= render 'form' %>
<%= link_to 'Back', buckets_path %>
</center>
</html>

app/views/buckets/index.html.erb
<html style="background-color:#b8b894;">
<center>
<h1 style="background-color: #00ff80;color:DodgerBlue">Buckets</h1>
<p style = "color:white">------------------------------------------------------------------------------------</p>
  <b style="color:white">|</b>

  <b> <%= link_to 'New buckets', new_bucket_path %> </b>
  <b style="color:white">|</b>
  <b><%= link_to 'Back ', controller: 'welcome' %></b>
    <b style="color:white">|</b>

<p style = "color:white">------------------------------------------------------------------------------------</p>
<table>  
<%= form_with scope: :bucket, url: buckets_path, local: true do |form| %>
<% end %>
  <tr>
    <th >Name</th>
    <th style="color:#ffffff;">|</th>
    <th>Description</th>

  </tr>
 
  <% @buckets.each do |bucket| %>
    <tr>
      <td><%= bucket.name %></td>
      <td style="color:#ffffff;">|</td>
      <td><%= bucket.description %></td>
      <td style="color:#ffffff;"> | </td>
      <td><%= link_to 'Show', bucket_path(bucket) %></td>
      <td style="color:#ffffff;"> | </td>
            <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
            <td style="color:#ffffff;"> | </td>
                  <td><%= link_to 'Delete', bucket_path(bucket),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>

</table>
</center>
</html>

app/views/buckets/new.html.erb
<html style="background-color:#b8b894;">
<center>

<h1 style="color:DodgerBlue; background-color:#00ff80;">New Bucket</h1>
  <h2 style="color:DodgerBlue; background-color:#00ff80;">Enter the details to create Buckets...</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', buckets_path %>

</center>
</html>

app/views/buckets/show.html.erb

<html style="background-color:#b8b894;">

<h2 style="color:Red

; background-color:#00ff80;">Bucket Details</h2>

<p>
  <strong>Name:</strong>
  <%= @bucket.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @bucket.description %>
</p>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %> |
<%= link_to 'Delete', bucket_path(@bucket),
 method: :delete,
data: { confirm: 'Are you sure?' } %>


<h2 style="color:DodgerBlue; background-color:#00ff80;">Add a Task to this bucket:</h2>
 <%= render 'tasks/form' %>

<h2 style="color:DodgerBlue; background-color:#00ff80;">Tasks</h2>
<table>
<tr>
<th style="color:#ffffff;">Name</th>
<th style="color:#ffffff;">|</th>
<th style="color:#ffffff;">Description</th>
<th style="color:#ffffff;">|</th>

</tr>
<%= render @bucket.tasks %>

</table>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rdtm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @bucket, @bucket.tasks.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<% if task.id != nil %>
<center>

<tr>
<td>
  <%= task.name %>
  </td>
  <td style="color:#ffffff;">|</td>
  <td>
  <%= task.description %>
  </td>
  <td style="color:#ffffff;">|</td>
  <td>
  <%= link_to 'Destroy Task', [task.Bucket, task],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
               </td>
<tr>

</center>
<%end%>

app/views/welcome/index.html.erb
<html style="background-color:#b8b894;">
<center>
<h1 style="color:DodgerBlue;background-color:#00ff80">
"Welcome to Railsdata TaskManager"
</h1>
<b>
<%= link_to '| CLICK HERE TO CREATE NEW BUCKET |', controller: 'buckets' %>
</b>
</center>
</html>